version: '3.8'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../backend
    container_name: backend
    restart: always
    volumes:
      - static_value:/app/backend_static
      - media_value:/app/backend_media
      - ../data:/app/data
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static
      - media_value:/var/html/backend_media
    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value:
