# Generated by Django 4.1.5 on 2023-03-03 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-id"]},
        ),
    ]
