# Generated by Django 4.1.5 on 2023-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_ingredient_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="amount",
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="amout",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
