# Generated by Django 4.1.5 on 2023-02-27 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="follower",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="followed",
            new_name="subscriber",
        ),
    ]
